GET http://localhost:8888/cart/1

###
GET http://localhost:8888/products
###
DELETE http://localhost:8888/cart/1/products/T-Shirt
###
DELETE http://localhost:8888/cart/1
###
POST http://localhost:8888/cart/products
Content-Type: application/json
  {
    
  }

###
GET http://localhost:8888/products
###
GET http://localhost:8888/checkout/generate-token/1

